茀
edward-martyr/Xdi8Translator pull request #6
Opened 2020-10-26 12:46 UTC by Kosmas131

'茀': 'y41L', #弗4iL，应为y4iL？

2020-10-28 02:44 UTC, edward-martyr requested changes
有道理，不过你的commit新增了一个`.idea`文件夹及一系列不需要的文件，能否将之删除？
再把`y41L`改为`y4iL`，我就可以pull了。

2020-10-29 04:07 UTC, Kosmas131 commented
我新提交了一个branch，删了.idea，不过多了个测试脚本……

2020-10-29 04:08 UTC, Kosmas131 commented
现在我fork的main分支应该可以了。希顶转汉字只能用于“分字连写”的情况，查不到的直接返回原文

2020-10-29 04:09 UTC, Kosmas131 commented
另外不知能否通过自定义结巴字典的方式，对希顶语词进行“分字”？

2020-10-29 04:09 UTC, closed without merging

2020-10-29 07:02 UTC, edward-martyr commented
> 另外不知能否通过自定义结巴字典的方式，对希顶语词进行“分字”？

自定义jieba词典可能还需要词频信息？否则自己直接写一个也行

2020-10-30 03:55 UTC, Kosmas131 commented
另外有个问题，多个汉字字符对应一个希顶语字符串，技术上能否实现？比如“纟火”对应“aho”，甚至还可以有“希顶”对应“xdi8”或者”xdi8 aho“（而非xE rdi8）

2020-10-31 02:07 UTC, edward-martyr commented
可以，只要放在單字節前面

2020-10-31 07:53 UTC, Kosmas131 commented
'麈': 'dvio', # 和”尘“同形，建议改为dka
'茀': 'y41L', #弗4iL，应为y4iL？
这两条应该没有问题。“思”字疑似两读？
另外建议tidai2xdi8增加"日": "T"